[package]
name = "dsconv"
version = "0.1.0"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2018"
description = "A data-serialization format converter"
readme = "README.adoc"
repository = "https://github.com/sorairolake/dsconv"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
atty = "0.2.14"
const_format = "0.2.14"
serde_json = { version = "1.0.64", features = ["preserve_order"] }
serde_yaml = "0.8.17"
structopt = "0.3.21"
toml = { version = "0.5.8", features = ["preserve_order"] }
