[package]
name = "dsconv"
version = "0.1.0"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2018"
description = "A data-serialization format converter"
readme = "README.adoc"
repository = "https://github.com/sorairolake/dsconv"
license = "Apache-2.0"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
atty = "0.2.14"
deser-hjson = "1.0.2"
dialoguer = { version = "0.8.0", default-features = false }
directories = "3.0.2"
indexmap = "1.7.0"
json5 = "0.3.0"
rmp-serde = "0.15.5"
rmpv = "0.4.7"
ron = { version = "0.6.4", features = ["indexmap"] }
serde = { version = "1.0.127", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = { version = "1.0.66", features = ["preserve_order"] }
serde_yaml = "0.8.17"
structopt = "0.3.22"
strum = { version = "0.21.0", features = ["derive"] }
toml = { version = "0.5.8", features = ["preserve_order"] }

[dev-dependencies]
assert_cmd = "2.0.0"
predicates = "2.0.2"

[profile.release]
lto = true
