= dsconv
:toc: macro

image:https://github.com/sorairolake/dsconv/workflows/CI/badge.svg[CI, link=https://github.com/sorairolake/dsconv/actions?query=workflow%3ACI]
image:https://img.shields.io/crates/v/dsconv[Version, link=https://crates.io/crates/dsconv]
image:https://img.shields.io/crates/l/dsconv[License, link=https://apache.org/licenses/LICENSE-2.0]

*dsconv* is a command-line utility for converting from one data-serialization format to another.

toc::[]

== Installation

=== Via a package manager

|===
|OS |Method |Package |Command

|Any
|Cargo
|https://crates.io/crates/dsconv[`dsconv`]
|`cargo install dsconv`
|===

=== Via pre-built binaries

Pre-built binaries for Linux, macOS and Windows are available on the https://github.com/sorairolake/dsconv/releases[release page].

=== How to build and install

Please see link:BUILD.adoc[].

== Usage

....
dsconv 0.2.0
A data-serialization format converter

USAGE:
    dsconv [FLAGS] [OPTIONS] [FILE]

FLAGS:
        --list-input-formats     List supported input formats
        --list-output-formats    List supported output formats
    -h, --help                   Prints help information
    -V, --version                Prints version information

OPTIONS:
    -f, --from <FORMAT>       Specify input format [possible values: CBOR, Hjson, JSON, JSON5, MessagePack, RON, TOML,
                              YAML]
    -t, --to <FORMAT>         Specify output format [possible values: CBOR, JSON, MessagePack, TOML, YAML]
    -o, --output <FILE>       Output to <FILE> instead of stdout
    -p, --pretty <BOOLEAN>    Output as a pretty-printed string [possible values: true, false]

ARGS:
    <FILE>    Input from <FILE>

See dsconv(1) for more details.
....

See link:doc/man/man1/dsconv.1.adoc[`dsconv(1)`] for more details.

== Changelog

Please see link:CHANGELOG.adoc[].

== Configuration

If you want to change the default behavior, you can use the configuration file.

See link:doc/man/man5/dsconv-config.toml.5.adoc[`dsconv-config.toml(5)`] for more details.

== Contributing

Please see link:CONTRIBUTING.adoc[].

== License

Copyright (C) 2021 Shun Sakai (see link:AUTHORS.adoc[])

This program is distributed under the terms of the _Apache License 2.0_.

See link:COPYING[] for more details.
