= dsconv

*dsconv* is a command-line utility for converting from one data-serialization format to another.

== Usage

....
dsconv 0.1.0
A data-serialization format converter

USAGE:
    dsconv [FLAGS] [OPTIONS] [FILE]

FLAGS:
    -h, --help                   Prints help information
        --list-input-formats     List supported input formats
        --list-output-formats    List supported output formats
    -V, --version                Prints version information

OPTIONS:
    -f, --from <FORMAT>       Specify input format [possible values: hjson, json, json5, toml, yaml]
    -o, --output <FILE>       Output to <FILE> instead of stdout
        --pretty <BOOLEAN>    Output as a pretty-printed string [possible values: true, false]
    -t, --to <FORMAT>         Specify output format [possible values: json, toml, yaml]

ARGS:
    <FILE>    Input from <FILE>
....

See the link:doc/man/man1/dsconv.1.adoc[man page] (`man dsconv`) for details.

== Configuration

If you want to change the default behavior, you can use the configuration file.

The location of the configuration file::

  * `$XDG_CONFIG_HOME/dsconv/config.toml` or `$HOME/.config/dsconv/config.toml` (Unix-like)
  * `$HOME/Library/Application Support/com.github.sorairolake.dsconv/config.toml` (macOS)
  * `%APPDATA%\sorairolake\dsconv\config.toml` (Windows)

See the link:doc/man/man5/dsconv-config.toml.5.adoc[man page] (`man dsconv-config.toml`) for details.

== How to build and install

Please refer to the link:INSTALL.adoc[Installation Guide].

== Contributing

Please refer to the link:CONTRIBUTING.adoc[Contribution Guide].

== License

Copyright (C) 2021 Shun Sakai (see link:AUTHORS.adoc[])

This program is distributed under the terms of the _Apache License 2.0_.

See link:COPYING[] for details.
