= dsconv
:toc: macro

image::https://github.com/sorairolake/dsconv/workflows/CI/badge.svg[CI, link=https://github.com/sorairolake/dsconv/actions]

*dsconv* is a command-line utility for converting from one data-serialization format to another.

toc::[]

== Installation

=== How to build and install

Please see the link:BUILD.adoc[Build Guide].

== Usage

....
dsconv 0.1.0
A data-serialization format converter

USAGE:
    dsconv [FLAGS] [OPTIONS] [FILE]

FLAGS:
        --list-input-formats     List supported input formats
        --list-output-formats    List supported output formats
    -h, --help                   Prints help information
    -V, --version                Prints version information

OPTIONS:
    -f, --from <FORMAT>       Specify input format [possible values: CBOR, Hjson, JSON, JSON5, MessagePack, RON, TOML,
                              YAML]
    -t, --to <FORMAT>         Specify output format [possible values: CBOR, JSON, MessagePack, TOML, YAML]
    -o, --output <FILE>       Output to <FILE> instead of stdout
    -p, --pretty <BOOLEAN>    Output as a pretty-printed string [possible values: true, false]

ARGS:
    <FILE>    Input from <FILE>

See dsconv(1) for more details.
....

See link:doc/man/man1/dsconv.1.adoc[`dsconv(1)`] for more details.

== Changelog

Please see the link:CHANGELOG.adoc[Changelog].

== Configuration

If you want to change the default behavior, you can use the configuration file.

See link:doc/man/man5/dsconv-config.toml.5.adoc[`dsconv-config.toml(5)`] for more details.

== Contributing

Please see the link:CONTRIBUTING.adoc[Contribution Guide].

== License

Copyright (C) 2021 Shun Sakai (see link:AUTHORS.adoc[])

This program is distributed under the terms of the _Apache License 2.0_.

See link:COPYING[] for more details.
