//
// SPDX-License-Identifier: Apache-2.0
//
// Copyright (C) 2021 Shun Sakai
//

= dsconv(1)
// Specify in UTC.
:docdate: 2022-04-19
:doctype: manpage
ifdef::revnumber[:mansource: dsconv {revnumber}]
:manmanual: General Commands Manual
:includedir: ../include

== NAME

dsconv - a data-serialization format converter

== SYNOPSIS

*{manname}* [_OPTION_]... [_FILE_]

== DESCRIPTION

*{manname}* is a command-line utility for converting from one
data-serialization format to another.
If _FILE_ is not specified, the input is read from stdin.

== OPTIONS

Unless otherwise noted, the value of each option is case-insensitive.

=== Conversion options

*-f*, *--from* _FORMAT_::
  Specify input format.
  This option can be omitted if the input file is specified and _FORMAT_ can be
  determined from the filename extension.

  Possible values:{blank}:::

    * *cbor* (CBOR)
    * *hjson* (Hjson)
    * *json* (JSON)
    * *json5* (JSON5)
    * *messagepack* (MessagePack)
    * *ron* (RON)
    * *toml* (TOML)
    * *yaml* (YAML)

*-t*, *--to* _FORMAT_::
  Specify output format.
  This option can be omitted if the output file is specified and _FORMAT_ can
  be determined from the filename extension.

  Possible values:{blank}:::

    * *cbor* (CBOR)
    * *json* (JSON)
    * *messagepack* (MessagePack)
    * *toml* (TOML)
    * *yaml* (YAML)

*--list-input-formats*::
  List supported input formats.

*--list-output-formats*::
  List supported output formats.

=== I/O options

*-o*, *--output* _FILE_::
  Output to _FILE_ instead of stdout.

*-p*, *--pretty* [*true*|*false*]::
  Output as a pretty-printed string.
  If the value is omitted, it is the same as selecting *true*.
  The value of this option is case-sensitive.
  This option is available when the output is JSON or TOML.
  Default is *false*.

*--color* _WHEN_::
  Specify when to use colored output.

  Possible values:{blank}:::

    * *auto* (display colors when the terminal is detected, default)
    * *always* (always display colors)
    * *never* (never display colors)

=== General options

*-h*, *--help*::
  Print help message and exit.

*-V*, *--version*::
  Print the version number and exit.

*--generate-completion* _SHELL_::
  Generate shell completion.
  The generated shell completion is output to stdout.
  To output as a shell completion file, specify the directory to store using
  *--output* _OUT_DIR_.

  Possible values:{blank}:::

    * *bash* (Bash)
    * *elvish* (Elvish)
    * *fish* (fish)
    * *powershell* (PowerShell)
    * *zsh* (Zsh)

== EXIT STATUS

If successful, return 0 as the exit status.
Otherwise, return non-zero as the exit status.

== EXAMPLES

Convert a JSON file to TOML:{blank}::
  $ *{manname} -t toml input.json*

include::{includedir}/section-reporting-bugs.adoc[]

include::{includedir}/section-copyright.adoc[]

== SEE ALSO

*bat*(1), *jq*(1), *dsconv-config.toml*(5)
